const nominations = {
  "1": {
    "id": 1,
    "date": "2022-08-19",
    "authorFirst": "James",
    "authorLast": "Pula",
    "authorEmail": "jpula@pnw.edu",
    "nomFirst": "Marie E.",
    "nomLast": "Zakrzewska",
    "nomYOB": "0",
    "category": "c700",
    "subcategory": "s708",
    "nomQ1": "q101,q102,q103,q104,q105",
    "nomQ1Description": "Marie Elizabeth Zakrzewska founded the New England Hospital for Women and Children in Boston in 1862. Its significance was threefold. First, there was no other institution of its kind offering clinical internship experience to women. Second, since the hospital was staffed exclusively by women physicians, it offered the opportunity, as she phrased it, \u201cto demonstrate that women could be successful physicians.\u201d Third, It was also unique as the first to offer clinical internships to women. Because of her efforts, many women, who would otherwise never have the opportunity, were able to enter the medical field. The hospital recorded another \u201cfirst\u201d when it hired Anita Tyng as a surgeon, the first time in American history that a woman was listed officially as specializing in surgery. In 1872, she established a nursing program, gaining recognition as the first general training school for nurses in America. One of the first graduates was Linda Richards who was the first formally trained nurse in the United States. She eventually became a leader in developing curricula for nursing training throughout the United States and participated in the organization of the Bellevue Training School in New York. In 1875 the New England Hospital graduated the first African-American nurse in the United States, Mary Elizabeth Mahoney. Other graduates included Dr. Mary Putnam-Jacobi, the first woman admitted to the prestigious School of Medicine in Paris; Dr. Sophia Jax-Blake who subsequently establishing the London School of Medicine for Women; and Dr. Elizabeth Mosher who went on to be appointed the First Dean of Students and Professor of Psychology at the University of Michigan. Due largely to her constant campaigning, in 1879 the all-male Massachusetts Medical Society, reluctantly voted to admit women to membership on equal terms with men. This was especially important because in Boston at the time city directories listed physicians under three categories\u2014\u201cMembers of the Massachusetts Medical Society,\u201d \u201cPhysicians,\u201d and \u201cPhysicians-Female.\u201d The Physicians-Female category included not only those with medical degrees but also clairvoyants, midwives, and others. To separate themselves from women marginally educated in medicine, if at all, and to have their medical expertise sanctioned by their peers, women physicians naturally sought comparable admittance to medical societies. This was a major breakthrough in legitimizing female physicians in the eye of the general public. Zakrzewska\u2019s pioneering efforts broke many barriers that opened the medical field to female practitioners at every level from nursing to surgeons.",
    "nomQ2": "q201,q202,q203",
    "nomQ2Description": "The female nurses and physicians trained at Zakrzewska's teaching hospital spread her influence throughout the US and internationally. Dr. Mary Putnam-Jacobi became the first woman admitted to the prestigious School of Medicine in Paris and founded the Association for the Advancement of the Medical Education of Women. Dr. Sophia Jex-Blake established the London School of Medicine for Women modeled on what she learned from Zakrzewska. Dr. Amanda Sanford Hickey, who interned at the New England Hospital, went on to become the first female graduate of the University of Michigan Medical School. Dr. Elizabeth Mosher became the first Dean of Students and Professor of Psychology at the University of Michigan, which founded its own nursing program. Linda Richard, after having studied and graduated from the New England Hospital Nursing School in 1873, went on to found other formal nursing schools and become a leader in nursing in the United States. She developed the first system for charting and maintaining individual patient medical records. Mary Elizabeth Mahoney in 1908 co-founded the National Association of Colored Graduate Nurses. As the first president of the New England Hospital Medical Society, the first medical society in the world formed by women, Zakrzewska exerted continuing pressure that led medical societies throughout the US to begin admitting female physicians and also led to the Johns Hopkins University establishing an endowment for female medical education and opening its doors to women in 1891. Historian Virginia Drachman, in her Hospital with a Heart: Women Doctors and the Paradox of Separatism at the New England Hospital 1862-1969, concluded that Zakrzewska \u201cturned the New England Hospital into one of the most important women\u2019s medical institutions in the nineteenth century.\u201d As such, it served as a model for women\u2019s medical education and practical application.",
    "nomQ3": "q301,q302",
    "nomQ3Description": "Zakrzewska participated actively, and was to a great extent responsible for, the realization in the United States of quality medical education for women, the gradual opening of professional doors to women seeking careers in medicine, and ultimately their acceptance into that profession. By 1900, almost one-fourth of Boston\u2019s physicians were women and three out of the four medical schools in that city allowed women to matriculate. By the same date, because of her efforts, medical schools across the United States were opening their doors to women and professional medical societies were recognizing them as coequals. As explained in #1 and #2 above, the influence of her efforts spread to other parts of the United States and to Europe. Graduates of the New England Hospital she founded and led established her ideas on quality medical education for women wherever their careers took them. In the same manner that Maya Lin's design for the Vietnam Veterans Memorial in Washington, DC, inspired a new way to imagine such commemorative statuary, in the same way that Jane Addams\u2019 creation of Hull House in Chicago sparked the settlement house movement, Marie Elizbeth Zakrzewska\u2019s establishment of the New England Hospital for Women and Children spawned a new era in health care for women as well as the education of female physicians and nurses. It was the initial undertaking whose success opened the medical profession to women and led to their acceptance as members of established professional medical societies.",
    "nomDeceased": "yes",
    "nomAchieved": "yes",
    "nomAdditionalDescription": "Zakrzewska was naturalized as a US citizen in the U.S. District Court in Boston on January 28, 1863. She was in the forefront of the fight for female acceptance into the charter of the Massachusetts Medical Society which allowed only male candidates. Women desired this recognition because of the acceptance of their professional qualifications it would inspire among the general public. The Boston city directories at the time listed three categories\u2014\u201cMembers of the Massachusetts Medical Society,\u201d \u201cPhysicians,\u201d and \u201cPhysicians-Female.\u201d The Physicians-Female category included not only those with a medical degree but also clairvoyants, midwives, and others. To separate themselves from women marginally educated in medicine, if at all, and to have their medical expertise sanctioned by their peers, women physicians naturally sought comparable admittance to medical societies. This was the first crack in this \"glass ceiling,\"which led other societies to also open their doors. In addition to her medical contributions, she cosponsored the publication of The Woman\u2019s Journal with Mary L. Booth and was an active participant in the anti-slavery crusade as a close collaborator with William Lloyd Garrison and the radical German editor Karl Heinzen. Her home at 5 Peter Parley Road in the Jamaica Plain area is listed as a site on the Boston Women\u2019s Heritage Trail. As an indication of her importance, more than a dozen articles have focused on her career and influence, as well as three major biographies: Isabel Ross, Child of Destiny: The Life Story of the First Woman Doctor (New York: Harper Brothers, 1949); Arleen Marcia Tuchman, Science Has No Sex: The Life of Marie Zakrzewska, M.D. (Chapel Hill, NC: University of North Carolina Press, 2006); and Agnes C. Vietor, ed., A Woman\u2019s Quest; The Life of Marie E. Zakrzewska, M.D. (New York: D. Appleton and Company, 1924)."
  },
  "2": {
    "id": 2,
    "date": "2022-08-23",
    "authorFirst": "Evelyn",
    "authorLast": "Cherry",
    "authorEmail": "hg3906@wayne.edu",
    "nomFirst": "Judith",
    "nomLast": "Heumann",
    "nomYOB": "0",
    "category": "c600",
    "subcategory": "s601,s604",
    "nomQ1": "q101,q102,q103,q104,q105",
    "nomQ1Description": "As Senior Fellow at the Ford Foundation (2017-2019), she wrote \u201cRoad Map for Inclusion: Changing the Face of Disability in Media.\u201d She also currently serves on a number of non-profit boards including the American Association of People with Disabilities,  the Disability Rights Education and Defense Fund,  Humanity and Inclusion, as well as the Human Rights Watch Board.\n\nJudy was a founding member of the Berkeley Center for Independent Living which was the first grassroots center in the United States and helped to launch the Independent Living Movement both nationally and globally.\nIn 1983, Judy co-founded the World Institute on Disability (WID) with Ed Roberts and Joan Leon, as one of the first global disability rights organizations founded and continually led by people with disabilities that works to fully integrate people with disabilities into the communities around them via research, policy, and consulting efforts.\n\nThe NEA Friend of Education Award is presented during NEA\u2019s annual convention and recognizes a person or organization whose leadership, acts or support have significantly contributed to the improvement of American public education. Judy Heumann was honored with the award in 2021.\n\nHeumann played a role in the development and implementation of groundbreaking legislation protecting the rights of children and adults with disabilities, including IDEA, Section 504 of the Rehabilitation Act, the Americans with Disability Act, and the Convention on the Rights of Persons with Disabilities.",
    "nomQ2": "q201,q202,q203",
    "nomQ2Description": "Judith Heumann is an internationally recognized leader in the disability community and a lifelong civil rights advocate for disadvantaged people. She has been appointed Special Advisor for International Disability Rights at the U.S. Department of State. She previously served as the Director for the Department on Disability Services for the District of Columbia, where she was responsible for the Developmental Disability Administration and the Rehabilitation Services Administration.\n\nFrom June 2002- 2006, Judith E. Heumann served as the World Bank's first Adviser on Disability and Development. In this position, Heumann led the World Bank's disability work to expand the Bank\u2019s knowledge and capability to work with governments and civil society on including disability in the Bank discussions with client countries; its country-based analytical work; and support for improving policies, programs, and projects that allow disabled people around the world to live and work in the economic and social mainstream of their communities. She was Lead Consultant to the Global Partnership for Disability and Development.\n\nFrom 1993 to 2001, Heumann served in the Clinton Administration as the Assistant Secretary for the Office of Special Education and Rehabilitative Services in the Department of Education. Heumann was responsible for the implementation of legislation at the national level for programs in special education, disability research, vocational rehabilitation and independent living, serving more than 8 million youth and adults with disabilities.\n\nFor more than 30 years, Heumann has been involved on the international front working with disabled people\u2019s organizations and governments around the world to advance the human rights of disabled people. She represented Education Secretary, Richard Riley, at the 1995 International Congress on Disability in Mexico City. She was a US delegate to the Fourth United Nations World Conference on Women in Beijing, China. She has been active with Disabled Peoples\u2019 International, Rehabilitation International and numerous Independent Living Centers throughout the world. She co-founded the Center for Independent Living in Berkeley California and the World Institute on Disability in Oakland California.",
    "nomQ3": "q301,q302",
    "nomQ3Description": "Judith (Judy) Heumann is an internationally recognized disability advocate. She served in the Clinton and Obama Administration and was a Senior Fellow at the Ford Foundation. Judy's story was also featured in the documentary \"Crip Camp: A Disability Revolution,\"a 2020 American award winning documentary film produced by the Obama Higher Ground Production. In 2020, she published her memoir \"Being Heumann: An Unrepentant Memoir of a Disability Rights Activist,\"written with Kristen Joiner. There is also a Young Adult version called \"Rolling Warrior.\"Judy is now the producer of The Heumann Perspective, a podcast and YouTube channel that aims to share the beauty of the disability community.",
    "nomDeceased": "no",
    "nomAchieved": "yes",
    "nomAdditionalDescription": "She has been featured in numerous documentaries including on the history of the disability rights movement, including Lives Worth Living and the Power of 504 and delivered a TED talk in the fall of 2016, \u201cOur Fight for Disability Rights- and Why We\u2019re Not Done Yet\u201d. Her story was also told on Comedy Central\u2019s Drunk History in early 2018, in which she was portrayed by Ali Stroker. "
  },
  "3": {
    "id": 3,
    "date": "2022-08-30",
    "authorFirst": "virginia",
    "authorLast": "Smith",
    "authorEmail": "ginsu1@comcast.net",
    "nomFirst": "Claire",
    "nomLast": "Aucoin",
    "nomYOB": "0",
    "category": "c800",
    "subcategory": "",
    "subcategory-description": "Service to women/Good Samaritan home in Colombia. She     is from henniker, nh originally, and continues to return there in the summer. She was instrumental  in arranging adoptions of many young children from columbia to the USA. St.theresa\u2019s church in henniker would have information. She is a saint for sure. Has impacted so many women and brought them from extreme poverty,abuse to a brighter future including housing and employable crafts. I cannot do justice to her extreme contributions here. She is in her 90\u2019s now.",
    "nomQ1": "q101,q102,q103,q104,q105",
    "nomQ1Description": "See above",
    "nomQ2": "q201,q202,q203",
    "nomQ2Description": "See above",
    "nomQ3": "q301,q302",
    "nomQ3Description": "Her contributions and life long efforts should be documented.",
    "nomDeceased": "no",
    "nomAchieved": "yes",
    "nomAdditionalDescription": "Her contributions and life long efforts should be documented."
  },
  "4": {
    "id": 4,
    "date": "2022-09-08",
    "authorFirst": "Scot",
    "authorLast": "Sunnergren",
    "authorEmail": "Scot@Sunnergren.com",
    "nomFirst": "Pauline",
    "nomLast": "Frederick",
    "nomYOB": "0",
    "category": "c800",
    "subcategory": "",
    "subcategory-description": "Journalism (Print and Television)",
    "nomQ1": "q101,q102,q103,q104,q105",
    "nomQ1Description": "Pauline Frederick is considered to be a pioneer of women in journalism. Her career, spanning over 50 years, saw her breaking into areas of journalism previously restricted to men. \n\nln 1954 Pauline Frederick received the Alfred I DuPont award, which honors excellence in broadcast journalism. The award, established in 1942 is considered the equivalent of the Pulitzer Prize and is administered by Columbia University. She went on to win the George Foster Peabody award for distinguished and meritorious public service by American radio and\ntelevision.",
    "nomQ2": "q201,q202,q203",
    "nomQ2Description": "By doing what she did, she paved the way for Marlene Sanders, Nancy Dickerson. and Marya McLaughlin to enter this male dominated field. The United States Government and Federal Communications Commission made affirmative action an important condition for station license renewal in 1971. Connie Chung, Andrea Mitchell, Jane Pauly, Diane Sawyer, Leslie Stahl and others then referred to themselves as the \"class of 1972\". They not only benefited from the US Government but also from women like Pauline Frederick who was the trailblazer for all women in network news.\n\nNationally, Pauline Frederick became a ground breaker for women in broadcast journalism.\n\nWhile writing scripts for A.B.C., reporter H.R. Baukage reportedly told her to \"stay away from radio, it doesn't like women.\"She told the New York Times \"she was seriously aware, however, that the general opinion in the radio world is that women can't broadcast news.\"This school of thought believes that a woman's voice doesn't carry authority.\n\nAt that time, no man would allow a woman to interview him, so she set about interviewing the wives of important men, and was hired by an editor to write a weekly feature which led to being hired by N.B.C. to do an occasional radio interview.\n\nHer list of firsts included first woman to receive Peabody, du Pont, Paul White awards, first woman to moderate a presidential debate, first women elected president of U.N. Correspondents Association, all common place now for women.\n\nGlobally, as a war correspondent, she reported on crises in Korea, Suez, Hungary, the Middle East, Lam Cambodia, the Congo, Cuba, Cypress, Dominican Republic and Vietnam.\n\nAs she became known as \"the voice of the U.N.\"she was relied on to help others understand clearly and concisely international news. After retiring in 1974 and becoming N.P.R.'s International Affairs Analyst, she was able to sort out the complexities for many.\n\n",
    "nomQ3": "q301,q302",
    "nomQ3Description": "There have been many contributors to the advancement ofwomen in the professional workforce. ln journalism specifically, the first, and arguably the greatest, was Pauline Frederick.\n\nPauline Frederick broke down the gender wall in journalism. ln the '1970's, there were still not many women in the industry. Some of her contemporaies of that time, such as Nancy Dickerson, Aline Saarlnen, Liz Trotta, Marya McLaughlin, Virginia Sherwood, Marlene Sanders, Connie Chung, Andrea Mlitchell, Jane Pauly, Diane Sawyer and Leslie Stahl owe\ntheir careers to the hard work that Pauline Frederick had been doing in the previous 40 years. Through sheer determination and love for what she was doing, Pauline contributed significantly to the advancement of women in the workforce through her work in national and international journalism.\n\nThe enduring value of her achievements throughout most of the 20rh century can easily be seen in our news today. ln both television and print, the role of women journalists in the world today is obvious. They are prolific and respected in this field. And they are all following in the footsleps of someone with the passion for reporting the news... Pauline Frederick.",
    "nomDeceased": "yes",
    "nomAchieved": "yes",
    "nomAdditionalDescription": "Pauline Frederick's foremost accomplishment was to be the first serious female news broadcaster.\n\nAt a time when women were reporting only social events, Pauline Frederick was inspired to become a broadcast journalist by two important people. At her high school graduation, Rev. Dr. John A.W. Haas urged women to take a larger role in world affairs. He said that girls are independent and have fire, dreams,  vision and courage. Then her history professor at American University, while getting her Master's degree in international law, suggested she combine her love for journalism and international affairs. She did just that, carving an unparalleled niche in broadcast journalism as a radio and television correspondent specializing in United Nations and International relations.\n\nIn 1948, the New York Times described her as \"only one of her kind\"and wrote that she did not want to be considered a \"woman reporter'', but a regular reporter judged on the merit of her work. She refrained from being temperamental, keeping her reporting objective and free of frills.\n\nThe Women's movement was not in full force yet, but she became an early participant because of her dreams.\n\nBy doing what she did, she paved the way for Marlene Sanders, Nancy Dickerson. and Marya McLaughlin to enter this male dominated field. The United States Government and Federal Communications Commission made affirmative action an important condition for station license renewal in 1971. Connie Chung, Andrea Mitchell, Jane Pauly, Diane Sawyer, Leslie Stahl and others then referred to themselves as the \"class of 1972\". They not only benefited from the US Government but also from women like Pauline Frederick who was the trailblazer for all women in network news.\n"
  },
  "5": {
    "id": 5,
    "date": "2022-09-12",
    "authorFirst": "Gabriella",
    "authorLast": "Rustin",
    "authorEmail": "lilliepad820@icloud.com",
    "nomFirst": "L. Keryl",
    "nomLast": "Rustin",
    "nomYOB": "1948",
    "category": "c200",
    "subcategory": "s201",
    "nomQ1": "q101,q102,q103,q104,q105",
    "nomQ1Description": "My grandma is 74 years. She is blind. She is  5K cross country running. She gives positivity.",
    "nomQ2": "q201,q202,q203",
    "nomQ2Description": "My grandma is a blind, 74 year old cross country 5k runner. She is the first blind 74 year old to run but she was 73. She has done a 5K at the National Senior Games Association in Ft Lauderdale FL 5/12/22.",
    "nomQ3": "q301,q302",
    "nomQ3Description": "My grandma is the president of a blind organization and 5K cross country runner. She is always willing to help kids and others. She is positive. People need to know a blind grandma can do running. My grandma did it.",
    "nomDeceased": "no",
    "nomAchieved": "yes",
    "nomAdditionalDescription": "My grandma is a positive person. She run 5-6 days a week. She has many medals. She went running during COVID. She run to help cancer people, homeless people and veterans. I am so proud of my grandma."
  },
  "6": {
    "id": 6,
    "date": "2022-09-13",
    "authorFirst": "Carolee",
    "authorLast": "Pearce",
    "authorEmail": "cjpgifts@gmail.com",
    "nomFirst": "Beverly",
    "nomLast": "French",
    "nomYOB": "0",
    "category": "c400",
    "subcategory": "s402",
    "nomQ1": "q101,q104",
    "nomQ1Description": "She has worked for 45 years in her high school and wins yearly awards for yearbooks and newspapers for her high school. She has been asked back each year that she could have retired. Her students and colleagues admire and adore her.",
    "nomQ2": "q201",
    "nomQ2Description": "She developed new techniques for publications of the yearbook from year to year focusing on prior year student accomplishments to get an historical view of student achievement and recognizes the relationship of siblings and parents in the historical review ion her yearbooks. It is very unique and appreciated by the relatives impacted by this honor.",
    "nomQ3": "q301",
    "nomQ3Description": "The focus on lineage of students and their relatives in the yearbook is a solid reminder of the importance of family in sma way that has not been done before.",
    "nomDeceased": "no",
    "nomAchieved": "yes",
    "nomAdditionalDescription": "Wonderful and caring and has given excessive hours above and beyond school hours and is a fixture day and night in the school to a assist students in her unique way of tracing generation after generation in the role of family in life not only school."
  },
  "7": {
    "id": 7,
    "date": "2022-09-13",
    "authorFirst": "Carolyn",
    "authorLast": "Maloney",
    "authorEmail": "carolyn.jm@yahoo.com",
    "nomFirst": "Sybil",
    "nomLast": "Shainwald",
    "nomYOB": "0",
    "category": "c800",
    "subcategory": "",
    "nomQ1": "q101,q102,q103,q104,q105",
    "nomQ1Description": "Sybil Shainwald\u2019s compassion and professional skills have ennobled the practice of law.\u201d These words of United States District Court Judge Jack B. Weinstein, before whom Ms. Shainwald appeared hundreds of times in championing her clients\u2019 rights, encapsulate her life and career. \n\nSince the beginning of her legal career, Sybil Shainwald has focused almost exclusively on women\u2019s health issues. Through her groundbreaking advocacy, she has advanced a deep commitment to social justice and women\u2019s rights. The list of landmark cases with which she has been involved is impressive. She was instrumental in expanding the statute of limitations for latent injuries and filed the first case under the Revival and Discovery Statute, thus making compensation possible for thousands of women and their children, whose injuries had been dismissed.\n\nSybil Shainwald was counsel in Bichler v. Lilly, the nation\u2019s first DES daughter victory, after which thousands of cases were successfully litigated on behalf of women injured by DES (a dangerous drug). \n\n\n",
    "nomQ2": "q201,q202,q203",
    "nomQ2Description": "Sybil Shainwald brought the initial cases for the lactation suppressant Parlodel and the pregnancy screening test Chorionic Villus Sampling, and has litigated thousands of other cases involving drugs and devices harmful to women and their children. She represented two thousand women in the Dalkon Shield class action against A.H. Robins, and represents all the women of the world in breast implant litigation. She was successful in setting up a $25 million fund for women outside the United States.\n\nMs. Shainwald has been a vocal opponent of the use of Norplant and DepoProvera: two long-acting contraceptives used especially in developing countries. She has been a force in the campaign for proactive education and information dissemination from Appalachia to Africa. She was chair of the National Women\u2019s Health Network; a founding member of Trial Lawyers for Public Justice; a member of the Food and Drug Administration\u2019s Consumer Consortium; an integral part of the First Black Women\u2019s Health conference, the first Rural Women\u2019s Health Conference, and many other grass roots women\u2019s groups, which she also helps fund.",
    "nomQ3": "q301,q302",
    "nomQ3Description": "Sybil Shainwald\u2019s professional writings, lectures, media appearances, and testimony before congressional committees and the FDA have raised the national consciousness on crucial women\u2019s health issues.\n\nMs. Shainwald has said her reason for going to law school was \u201cto make a perfect world, and in this I\u2019ve been eminently unsuccessful.\u201d If, as the Hebrew sages state, \u201cto save a life is to save the world,\u201d Ms. Shainwald has in fact been eminently successful, in that her pioneering advocacy on behalf of women\u2019s health has saved many lives.\n\nAt 94, Sybil Shainwald is still involved in activism for women and causes.  \n",
    "nomDeceased": "no",
    "nomAchieved": "unsure",
    "nomAdditionalDescription": ""
  },
  "8": {
    "id": 8,
    "date": "2022-09-15",
    "authorFirst": "Jim",
    "authorLast": "Duff",
    "authorEmail": "jkduff@comcast.net",
    "nomFirst": "Elizabeth",
    "nomLast": "Packard",
    "nomYOB": "0",
    "category": "c600",
    "subcategory": "s601",
    "nomQ1": "q102,q103,q104,q105",
    "nomQ1Description": "Elizabeth Packard was committed to the Illinois State Hospital in Jacksonville by her husband because of \"excessive application of body and mind\"in 1860. Many other women suffered the same fate for behavior such as \"novel reading, incessant talking, unusual zealousness, and strong will\"considered problematic by their husbands. Mrs. Packard was released after being kept in the facility for three years. A jury found that she had never been insane and she published pamplets, papers and small booklets which positively affected public sentiment and the law.",
    "nomQ2": "q201,q202,q203",
    "nomQ2Description": "Mrs. Packard crowd-funded her book (asked people to pay in advance) before this was a common practice and she did not have the funds for publishing since her husband retained all family funds - women did not have a right to even their own inheritance from family at this time.",
    "nomQ3": "q301,q302",
    "nomQ3Description": "\"On May 16, 1865, the Massachusetts legislature had amended the insanity law. Partly thanks to Elizabeth's impassioned campaign\"\n\"By her own reckoning, she secured the passage of thirty-four bills in forty-four legislatures across twenty-four states. She campaigned for women's equal right snd for the rights of the mentally ill.\"\nQuotes from \"The Woman They Could Not Silence: The shocking story of a woman who dared to fight back\"by Kate Moore, copyright 2021, 2022.",
    "nomDeceased": "yes",
    "nomAchieved": "yes",
    "nomAdditionalDescription": "I highly recommend reading the book, \"The Woman They Could Not Silence: The shocking story of a woman who dared to fight back\""
  },
  "9": {
    "id": 9,
    "date": "2022-09-16",
    "authorFirst": "Mary",
    "authorLast": "von Liski",
    "authorEmail": "mvonliski@yahoo.com",
    "nomFirst": "Elizabeth",
    "nomLast": "Packard",
    "nomYOB": "0",
    "category": "c800",
    "subcategory": "",
    "nomQ1": "q101,q103,q104",
    "nomQ1Description": "Elizabeth Packard's writing inspires others and relates to the importance of learning.",
    "nomQ2": "q201,q202",
    "nomQ2Description": "Change is vital in the way people react and act and treat others.",
    "nomQ3": "q301,q302",
    "nomQ3Description": "Reading her wisdom is valuable food for thought.",
    "nomDeceased": "no",
    "nomAchieved": "unsure",
    "nomAdditionalDescription": ""
  },
  "10": {
    "id": 10,
    "date": "2022-09-16",
    "authorFirst": "KAREN",
    "authorLast": "ACKLEY",
    "authorEmail": "krn.ackley@gmail.com",
    "nomFirst": "Elizabeth",
    "nomLast": "Packard",
    "nomYOB": "0",
    "category": "c400,c600,c700",
    "subcategory": "s601,s602,s708",
    "nomQ1": "q102,q103,q105",
    "nomQ1Description": "After being wrongfully institutionalized as insane by her husband and then later defending her sanity at trial in 1864, Packard campaigned to ensure the rights of the mentally ill as well as those of married women. She publicized the story of her hospitalization at the hands of her husband in order to prevent the abuse and neglect of others vulnerable before the law.",
    "nomQ2": "q202",
    "nomQ2Description": "Packard campaigned for legislation in Illinois and numerous other states that would ensure the rights of those in mental health hospitals and bolster the rights of married women. In Iowa, Maine, and Massachusetts, she helped win the fight for regular visiting teams that monitored conditions in asylums. In Iowa, \u201cPackard\u2019s Law\u201d made it illegal for asylum officials to intercept patients\u2019 mail. Packard won reforms to commitment laws in four states, as well as the passage of a law protecting married women\u2019s property in Illinois. Packard published books detailing her ordeal and gave speeches in order to garner publicity for her campaigns. In 1869, she convinced the courts to award her custody of her three younger children. She supported her children, as well as her reform efforts, with the proceeds from her writings. Packard\u2019s nationwide lobbying efforts continued through the 1880s. Throughout her many campaigns, she faced opposition from the increasingly organized and powerful psychiatric profession, but she continued.",
    "nomQ3": "q301,q302",
    "nomQ3Description": "Despite strong opposition from the psychiatric community, Packard's laws were passed in state after state, with lasting impact on commitment and care of the mentally ill in the United States.",
    "nomDeceased": "yes",
    "nomAchieved": "yes",
    "nomAdditionalDescription": ""
  },
  "11": {
    "id": 11,
    "date": "2022-09-17",
    "authorFirst": "Susan",
    "authorLast": "Daniel",
    "authorEmail": "sd386@cornell.edu",
    "nomFirst": "Serena",
    "nomLast": "Williams",
    "nomYOB": "0",
    "category": "c200",
    "subcategory": "s201,s202",
    "nomQ1": "q101,q105",
    "nomQ1Description": "Given her retirement this year and her endurance of so many slights she is epitome of resilience and grace that inspires mnay",
    "nomQ2": "q201,q202,q203",
    "nomQ2Description": "International tennis superstar and women\u2019s rights and equality in sports",
    "nomQ3": "q301,q302",
    "nomQ3Description": "She broke many glass ceilings in sports for women",
    "nomDeceased": "no",
    "nomAchieved": "yes",
    "nomAdditionalDescription": ""
  },
  "12": {
    "id": 12,
    "date": "2022-09-17",
    "authorFirst": "Tolani",
    "authorLast": "Aliyu",
    "authorEmail": "tolanij7@yahoo.com",
    "nomFirst": "Claudette",
    "nomLast": "Colvin",
    "nomYOB": "0",
    "category": "c600",
    "subcategory": "s601",
    "nomQ1": "q102,q103",
    "nomQ1Description": "Before Rosa Parks, there was Claudette Colvin, a 15 year old woman who refused to give up her seat on the bus. Her story is overshadowed because she was dark-skinned and pregnant, and civil rights leaders did not think she would be a good image for the movement.",
    "nomQ2": "q202,q203",
    "nomQ2Description": "Before Rosa Parks, there was Claudette Colvin, a 15 year old woman who refused to give up her seat on the bus. Her story is overshadowed because she was dark-skinned and pregnant, and civil rights leaders did not think she would be a good image for the movement.",
    "nomQ3": "q301",
    "nomQ3Description": "Before Rosa Parks, there was Claudette Colvin, a 15 year old woman who refused to give up her seat on the bus. Her story is overshadowed because she was dark-skinned and pregnant, and civil rights leaders did not think she would be a good image for the movement.",
    "nomDeceased": "yes",
    "nomAchieved": "yes",
    "nomAdditionalDescription": ""
  },
  "13": {
    "id": 13,
    "date": "2022-09-17",
    "authorFirst": "Gillian",
    "authorLast": "Friedlander",
    "authorEmail": "friedlander27@gmail.com",
    "nomFirst": "Carla",
    "nomLast": "Hayden",
    "nomYOB": "0",
    "category": "c400,c500,c600",
    "subcategory": "s403,s502",
    "nomQ1": "q101,q104",
    "nomQ1Description": "Hayden is the current librarian of Congress. She's the first woman and the first African American to hold the position.",
    "nomQ2": "q201,q202",
    "nomQ2Description": "Hayden has held numerous positions of leadership within the field. She was the second African American to hold the title of CEO at the Enoch Pratt public library.",
    "nomQ3": "q301",
    "nomQ3Description": "She helped end the FBI's rule that allowed access to private citizen's public library records. She worked ro overturn the law requiring filters and censorship on public library computers. She's been a champion for civil rights and the freedom of information.",
    "nomDeceased": "no",
    "nomAchieved": "yes",
    "nomAdditionalDescription": "The library field is a majority white field. It's very rare to see African American librarians, much less those in high positions of power. This is a remarkable feat. She's paving the way for a whole new set of leaders."
  },
  "14": {
    "id": 14,
    "date": "2022-09-17",
    "authorFirst": "Karen",
    "authorLast": "Johnson",
    "authorEmail": "johnsonkm@tds.net",
    "nomFirst": "Pat",
    "nomLast": "Summitt",
    "nomYOB": "0",
    "category": "c200,c400",
    "subcategory": "s203,s204",
    "nomQ1": "q101,q102,q103,q104,q105",
    "nomQ1Description": "Pat Summitt was the first NCAA basketball coach to reach the 1,000-win plateau making her the winningest basketball coach in NCAA history at the time. During her illustrious 38-year career (1974-2012) as the legendary collegiate women's coach of the University of Tennessee Lady Volunteers, Pat Summitt accrued an astonishing 1,098 wins, the most in college basketball history at the time of her retirement.\n\nShe raised the bar of excellence in the women's collegiate basketball at every turn making the UT program well known and respected on the world stage. Her incredible victory total included eight NCAA championship titles and 32 Southeastern Conference titles. During her tenure as coach of the Tennessee Lady Volunteers, she never missed the NCAA Tournament nor did she ever have a losing season. Summitt, who won silver as a player at the 1976 Olympics and coached the 1984 U.S. team to gold, subsequently directed 14 UT players who made Olympic teams. Noteworthy, Summitt's steadfast passion was developing young women into champions, graduates and successful citizens, and she was phenomenal in this endeavor. The Lady Vols were highly successful as athletes but astonishingly her program was perfect in graduating players. She had a 100% graduation rate for all student athletes who completed their eligibility as Lady Vols.",
    "nomQ2": "q201,q202,q203",
    "nomQ2Description": "Summitt constantly challenged each of her players to reach her potential as a student and an athlete establishing a code of conduct she called her \"Definite Dozen\"to encourage her players to embrace these tenets: Respect yourself and others. Take full responsibility. Develop and demonstrate loyalty. Learn to be a great communicator. Discipline yourself so no one else has to. Make hard work your passion. Don't just work hard, work smart. Put the team before yourself. Make winning an attitude. Be a competitor. Change is a must. Handle success like you handle failure. Summitt knew these traits were applicable for developing educated, self-sufficient young women to send into the world. She was a role model to many of her players and a total of 74 Lady Vols who Summitt mentored in the UT program went on to basketball coaching in the professional, college or high school ranks. \n\nIn 2011 at the age of 59 Summitt was diagnosed with early-onset Alzheimer's disease by physicians at the Mayo Clinic. Raising the bar on fearlessness, she  bravely revealed to the public the toughest opponent she ever confronted, early onset dementia, \"Alzheimer's Type.\"Despite this devastating news, she continued her coaching duties for the 2011\u20132012 season leading her team to win their sixteenth SEC championship in March 2012. Courageously she used the dire circumstances to educate and empower others about the disease. That same year, Summitt launched the Pat Summitt Foundation dedicated to finding a cure for Alzheimer's with proceeds going toward cutting-edge research. In 2015 The Pat Summitt Foundation and the University of Tennessee Medical Center announce a partnership to establish the Pat Summitt Alzheimer's Clinic.",
    "nomQ3": "q301,q302",
    "nomQ3Description": "Pat Summitt, the matriach of modern women's basketball, changed the landscape for female athletes. Throughout her coaching career, she seized the potential of female collegiate basketball striving to constantly move the game forward. She mandated that opportunities be created that advocated inclusivity to women athletes. Her pioneering vision transcended the game of basketball on the court and beyond. Her nurturing spirit has positively imparted guidance and wisdom on her Lady Vols, fans and the general public with enduring positive impact. \n\nHer honors are numerous, highlighted by the Presidential Medal of Freedom along with induction into the Women\u2019s Basketball Hall of Fame and the Naismith Memorial Basketball Hall of Fame.",
    "nomDeceased": "yes",
    "nomAchieved": "yes",
    "nomAdditionalDescription": "Pat Summitt has been my hero for nearly 5 decades now. In 1975 I moved to Knoxville to attend graduate school. My favorite pastime was attending Lady Vol basketball games and watching young Pat Summitt lead her players by example, sheer determination, and grit. I have read all three of her books which have inspired me to move forward despite challenges and setbacks. \n\nA few weeks ago I had the opportunity to visit the wonderful National Women's Hall of Fame in Seneca Falls, NY. After touring the museum, I felt compelled to nominate Pat Summitt for consideration as a new inductee to the National Women's Hall of Fame because of the enduring value of her lifetime achievements. By doing so, it is my hope that she will be thoughfully considered for nomination as an inductee. Her legacy, teachings, bravery, competitive spirit and love for the game of basketball are extraordinary and worthy of such an esteemed honor."
  },
  "15": {
    "id": 15,
    "date": "2022-09-18",
    "authorFirst": "Sharon",
    "authorLast": "Krebs",
    "authorEmail": "sharonkrebs@hotmail.com",
    "nomFirst": "Sally",
    "nomLast": "Priesand",
    "nomYOB": "0",
    "category": "c400,c800",
    "subcategory": "",
    "nomQ1": "q101,q102,q103,q104,q105",
    "nomQ1Description": "She is the first female rabbi ordained by a rabbinical seminary and second formally ordained rabbi in American Jewish history.",
    "nomQ2": "q201,q202,q203",
    "nomQ2Description": "Historically in the world of Judaism with few exceptions such as with fund raising or sisterhood, men were the dominant force and women had to end up taking the back seat. That changed when a Chicago area born woman was ordained as the first female cantor in America.  So by the same token, can't a formally ordained female rabbi in the Jewish world do the same job as good as a man?",
    "nomQ3": "q301",
    "nomQ3Description": "The rabbi has set a precedent and that said for example, there is a woman here in Buffalo, NY that is now both a Cantor (Reform) and a Rabbi in the Conservative Movement.  Finally, there is a 2005 film (\"And the Gates Opened: Women in the Rabbinate\") in which Priesand was interviewed.",
    "nomDeceased": "no",
    "nomAchieved": "yes",
    "nomAdditionalDescription": "The Rabbi Sally J. Priesand Award given by the Women of Reform Judaism was created initially to honor the 45th anniversary of Priesand's ordination. The award is given out once every year to a graduating Hebrew Union College-Jewish Institute of Religion Cincinnati campus woman, chosen because she exemplifies the mission and values of WRJ and embodies the qualities that Rabbi Priesand has exhibited throughout her career, including her clarity of vision, her commitment to excellence, her professionalism, her dedication to the continuity of Reform Judaism, her passion, and her perseverance."
  },
  "16": {
    "id": 16,
    "date": "2022-09-22",
    "authorFirst": "carole",
    "authorLast": "Hoyem",
    "authorEmail": "carolehoyem@aol.com",
    "nomFirst": "Elizabeth",
    "nomLast": "Packard",
    "nomYOB": "0",
    "category": "c500,c700",
    "subcategory": "s504,s708",
    "nomQ1": "q101,q102,q103,q104,q105",
    "nomQ1Description": "In 1860 Elizabeth Packard was the victim of a patriarchal society which allowed her dictatorial husband to commit her to an institution for the insane because she disagreed with him. She suffered greatly, but displayed her humanity in helping other women. Elizabeth went on to help reform the medieval practices of involuntary committal to asylums of women.",
    "nomQ2": "q201,q202,q203",
    "nomQ2Description": "Elizabeth Packard formed The Anti-Insane Asylum Society and also campaigned for divorced women to have custody of their children.",
    "nomQ3": "q301,q302",
    "nomQ3Description": "Elizabeth Packard exposed the cruel, brutal practices of treatment of women that led to a nascent revolution in society and psychology.",
    "nomDeceased": "yes",
    "nomAchieved": "yes",
    "nomAdditionalDescription": "No futher comments are necessary"
  },
  "17": {
    "id": 17,
    "date": "2011-09-24",
    "authorFirst": "Eren",
    "authorLast": "Slatcher-Burby",
    "authorEmail": "erin.burby07@gmail.com",
    "nomFirst": "Nicque",
    "nomLast": "Marina",
    "nomYOB": "0",
    "category": "c500",
    "subcategory": "s504",
    "nomQ1": "q104,q105",
    "nomQ1Description": "Nicque Marina is an inspirational woman mainly found on social media. She speaks on large issues and hidden issues within media and the world in general. She's an actor and a singer, and she uses her platform to uplift women, as well as hold people accountable for their actions.",
    "nomQ2": "q202",
    "nomQ2Description": "She exposed a high-ranking officer in the Air Force who was abusing their position of power to manipulate and mentally damage those under her authority, Nicque included. She exposed the poor handling of people like that within the military, and the blatant sexism and racism.",
    "nomQ3": "q301",
    "nomQ3Description": "She brought to the public's attention how the military treats the minorities within their ranks, and does nothing when their higher-ups abuse their power. She explores the harmful ideas and stereotypes in media, and spreads awareness. She is not afraid to speak her mind when treated unfairly, or when she sees something wrong.",
    "nomDeceased": "no",
    "nomAchieved": "yes",
    "nomAdditionalDescription": "She is on many platforms such as YouTube and Instagram."
  },
  "18": {
    "id": 18,
    "date": "2022-09-26",
    "authorFirst": "Estelle",
    "authorLast": "McDoniel",
    "authorEmail": "emcdinaz@me.com",
    "nomFirst": "Alene",
    "nomLast": "Duerk",
    "nomYOB": "0",
    "category": "c600",
    "subcategory": "c603",
    "nomQ1": "q102,q103,q105",
    "nomQ1Description": "I refer you to her updated biography, the ebook, titled \"Registered Nurse to Rear Admiral...A First for Navy Women\"",
    "nomQ2": "q201,q202",
    "nomQ2Description": "Fifty years ago one dedicated nurse, an RN, was selected by the US Navy to be the first woman to advance to an Admiral's rank. The US Congress gave the Navy permission to advance a woman to an Admiral's rank but it took the Navy men nearly five years to do so. \n\nBecoming a Rear Admiral opened the way for other women to reach a higher rank in the Navy. In addition, the fact that a nurse was the person who received this high honor recognized the importance and contributions nurses made and continue to make to both military and civilian lives.",
    "nomQ3": "q301,q302",
    "nomQ3Description": "Over fifty Navy women have reached an Admiral's rank.",
    "nomDeceased": "yes",
    "nomAchieved": "yes",
    "nomAdditionalDescription": "I believe the updated biography of Alene Duerk provides the reader with an understanding of the importance of women in the Navy, nurses in our society, and the benefit of being retired and still serving one's community. It also mentions honors Alene received.\nThe State of Ohio recently named a section of an Ohio highway in her honor."
  },
  "19": {
    "id": 19,
    "date": "2022-09-26",
    "authorFirst": "Edith",
    "authorLast": "Wacksman",
    "authorEmail": "dswacks@hotmail.com",
    "nomFirst": "Elizabeth",
    "nomLast": "Packard",
    "nomYOB": "0",
    "category": "c500",
    "subcategory": "s504",
    "nomQ1": "q103,q105",
    "nomQ1Description": "She changed laws that allowed men to unjustly put their wives in asylums. Never was quiet about injustice toward married women !",
    "nomQ2": "q202,q203",
    "nomQ2Description": "Was a change agent for married women when they had no voice!",
    "nomQ3": "q301,q302",
    "nomQ3Description": "Changed laws to give women a voice in legal matters.",
    "nomDeceased": "yes",
    "nomAchieved": "yes",
    "nomAdditionalDescription": "Look at the  book Thev\n Woman they could  not silence \nby Kate Moore"
  },
  "20": {
    "id": 20,
    "date": "2022-09-26",
    "authorFirst": "Barbara",
    "authorLast": "Jezioro",
    "authorEmail": "barbarajezior@aol.com",
    "nomFirst": "Cornelia",
    "nomLast": "Bentley sage Quinton",
    "nomYOB": "1876",
    "category": "c100",
    "subcategory": "s102,s107",
    "nomQ1": "q101,q103,q104,q105",
    "nomQ1Description": "Cornelia Bentley Sage Quinton (October 3, 1876 \u2013 May 16, 1936) was an American painter and curator. She was the director of the Albright Art Museum in Buffalo, New York from 1910 through 1924. Upon her appointment as director on October 15, 1910 she became the first woman to serve as director of a major art museum in the United States.\nIn 1920 Quinton received Cross of the Legion of Honor from France for her work promoting French art during WWI.\nQuinton left the Albright Art Museum in 1924 to become the first director of California Palace of the Legion of Honor, a position she held until 1930.",
    "nomQ2": "q201,q202",
    "nomQ2Description": "Quinton organized noteworthy exhibitions at Albright Art Museum such as the International Exhibition of Pictorial Photography in 1910, and the Exhibition of Contemporary American Sculpture in 1916.\nThe International Exhibition of Pictorial Photography was the first photography exhibition held at an American museum. The Exhibition of Contemporary American Sculpture featured more than 800 works of sculpture by 168 contemporary American artists.",
    "nomQ3": "q301",
    "nomQ3Description": "Quinton literally propelled the Albright Art Museum into the 20th century, by sponsoring major exhibits and used her contacts both here and abroad to have major works lent to the institution.",
    "nomDeceased": "yes",
    "nomAchieved": "yes",
    "nomAdditionalDescription": "Quinton was a true pioneer in what was and still is, a male dominated field.  It is amazing to me that she was not only a director of om=ne major museum, but two."
  },
  "21": {
    "id": 21,
    "date": "2022-09-30",
    "authorFirst": "Nicole",
    "authorLast": "Kellogg",
    "authorEmail": "nikki.kellogg72@gmail.com",
    "nomFirst": "Minna",
    "nomLast": "Schmidt",
    "nomYOB": "0",
    "category": "c100",
    "subcategory": "s109",
    "nomQ1": "q101",
    "nomQ1Description": "Wrote a book titled \"400 Outstanding Women of the World and Costumology of Their Time\".\nOwned the largest costume rental business in the early 1900s.\nOpened the Chicago Schmidt College of Scientific Costuming for the research and reconstruction of costumes.\nFor the 400 women in the book, she produced figurines for each of them for the 1933 World\u2019s Fair, illustrating women in ethnic apparel. \nLectured at the University of Chicago in the department of home economics from 1930-1937.\nEarned her Masters Degree from Kent School of Law in 1929, her thesis was entitled \u201cAncient Laws and Customs and the Evolution of the Status of Women.\u201d Her intention, she told the Pontiac Chautauqua, was not to use her degree to practice law, but to do \u201csimple, helpful things for the good of humanity.\u201d \nReferred to as the \"Fairy Godmother of Chigaco.\"",
    "nomQ2": "q201",
    "nomQ2Description": "Minna was very accomplished in her business and costuming, and her figurines have been donated to several museums, including Chicago History Museum, Illinois State Museum, Trinity Washington University, and supposedly the Smithsonian.\nSchmidt dedicated her later life to philanthropy by financing a hospital for women and children in her native Sindelfingen, Germany.",
    "nomQ3": "q302",
    "nomQ3Description": "Not sure how to answer this one. Since these events were 75-100 years ago, I believe Minna helped and inspired many women with her dedication to her business and to helping other women, especially with the financial funding of the women's hospital in Germany.",
    "nomDeceased": "yes",
    "nomAchieved": "unsure",
    "nomAdditionalDescription": "Minna is my great great grandmother, and my mom and I have been trying to collect her figurines so they can be kept in the family (every single one she made was donated out to businesses or museums). We'd be happy to donate one to your museum as well if Minna is nominated. \nHere is an excellent article about her at https://www.glessnerhouse.org/story-of-a-house/2022/3/15/minna-schmidt-and-costumology-an-american-success-story\nThank you for your consideration,\nNikki"
  },
  "22": {
    "id": 22,
    "date": "2022-10-03",
    "authorFirst": "Debradawn",
    "authorLast": "Shockey",
    "authorEmail": "shockeydebradawn@gmail.com",
    "nomFirst": "Helen",
    "nomLast": "Hunt Jackson",
    "nomYOB": "0",
    "category": "c400",
    "subcategory": "s403",
    "nomQ1": "q101,q102,q103,q104,q105",
    "nomQ1Description": "Helen Hunt Jackson, one of America\u2019s most popular women writers of her day, called for changes in the government\u2019s Indian policies in her book \u201cRamona\u201d. In 1882, Jackson became the first woman to hold the position of Special Commissioner of Indian Affairs as appointed by President Chester A. Arthur. The novel\u2019s success not only transformed the way people viewed the issue of Indian rights in America, but it also created a romantic vision of California that still lives on today through the annual production of the \"Ramona Outdoor Play\u201d.",
    "nomQ2": "q201,q202,q203",
    "nomQ2Description": "Hunt published A Century of Dishonor in 1881 as a factual, uncompromising account of the history of broken treaties and systemic mistreatment of American Indians by the United States. Hunt saw A Century of Dishonor as a means of documenting and changing America's relationship with American Indians, and in 1881, at her own expense, she sent inscribed copies to every member of Congress. The inscription read, \"Look upon your hands: they are stained with the blood of your relations.\"However, with its intellectual appeal, A Century of Dishonor failed to produce an emotional response to the Indian Question. Hunt described her next book, Ramona, as \"a way to move people's hearts\". She described her audience as those who \"will read a novel when they will not read serious books.\"Hunt hoped Ramona would do for Indians what Harriet Beecher Stowe's equally sentimental Uncle Tom's Cabin had done for African Americans, and she wrote to her friend Thomas Wentworth Higginson that \"The success of it, if it succeeds, will be that I do not even suggest any Indian history till the interest is so aroused in the heroine and hero, that the people will not want to lay the book down\"",
    "nomQ3": "q301,q302",
    "nomQ3Description": "In the two decades following its publication,\u00a0Ramona\u00a0was described as \"an exquisite work of art\"(Byers, p. 209) and \"unquestionably the best novel yet produced by an American woman\"(Byers, p. 229).\u00a0Ralph Waldo Emerson\u00a0and Higginson ranked Hunt among the best women writers of the period (Byers, p. 228). Among Indian rights groups\u00a0Ramona\u00a0and Hunt came to enjoy the kind of influence Hunt had hoped for the novel. The Women's National Indian Association established the Ramona Mission among the California Indians (Mathes,\u00a0Helen Hunt Jackson,\u00a0p. 92), and the novel influenced the 1887 passage of the Dawes Act, which provided for individual allotment of tribal lands and was believed by many liberal thinkers at the time to be the first step toward the eventual assimilation of Indians into American society as equals. In 1923 the Ramona Pageant began in the southern California town of Hemet. The pageant featured a staged production of\u00a0Ramona\u00a0that is currently billed as both the Official California State Play and the Longest Running Outdoor Drama in America. Most important for southern California, the novel inspired what has been called the \"Ramona boom,\"an influx of tourists seeking the California depicted in the novel. A report in 1916 noted that over 50 million tourism dollars could be directly linked to the popularity of\u00a0Ramona\u00a0(May,\u00a0The Annotated Ramona,\u00a0p. 231). Everything from olive and fruit groves to a Catholic convent has honored the novel by taking its name.",
    "nomDeceased": "yes",
    "nomAchieved": "yes",
    "nomAdditionalDescription": "The first year of the annual play, \"Ramona\", was 1923 in the beautiful hills of Hemet, California. The next performance, in April 2023, will be the 100th anniversary of \"Ramona\", California's Official State Play. Helen Hunt Jackson was inducted into the Colorado Women's Hall of Fame in 1985, but I would love to see her induction into the National Women\u2019s Hall of Fame, now. It's time. I have been informed that the nominations judging process has already been completed, and the process of finalizing the 2023 Inductees is already underway. Therefore getting Miss Helen Hunt Jackson\u2019s induction lined up with the 100th\u00a0anniversary of \u201cRamona\u201d and the subsequent celebration of her remarkable life will not be possible in 2023. I am hoping my nomination of Helen Hunt Jackson will be considered for the following Induction cycle of 2024, as, for us, every year is a celebration of Helen Hunt Jackson's incredible contributions to our world!"
  },
  "23": {
    "id": 23,
    "date": "2022-10-08",
    "authorFirst": "Joan",
    "authorLast": "Seaman",
    "authorEmail": "cjseaman5550@gmail.com",
    "nomFirst": "Pat",
    "nomLast": "Summitt",
    "nomYOB": "0",
    "category": "c200",
    "subcategory": "s201,s203",
    "nomQ1": "q101,q102,q103,q104,q105",
    "nomQ1Description": "She was the winningest coach in the history of women's basketball.\nAcruing 1098 career wins. The most college basketball history at the time of her retirement Her success as head coach at the University of Tennessee Womens Basketball Team heighten the country\u2019s awareness of women\u2019s basketball.",
    "nomQ2": "q201,q202,q203",
    "nomQ2Description": "See previous statements.\nShe won 8 NCAA championships for the University of Tennessee. Her character and impression on her players instilled morale and ethical values that many held as they went on to careers after their playing time.",
    "nomQ3": "q301,q302",
    "nomQ3Description": "Pat Summitt was diagnosed with early onset Alzheimer's and came out publicly about her disease. She very graciously retired before her condition worsen and shed light on this disease.",
    "nomDeceased": "yes",
    "nomAchieved": "yes",
    "nomAdditionalDescription": "Her success in basketball was not only on a national level, but also on an international level."
  },
  "24": {
    "id": 24,
    "date": "2022-10-09",
    "authorFirst": "Rita",
    "authorLast": "Brock",
    "authorEmail": "rnbrock50@gmail.com",
    "nomFirst": "Margaret",
    "nomLast": "Kibben",
    "nomYOB": "0",
    "category": "c600",
    "subcategory": "s603,s604",
    "nomQ1": "q101,q102,q103,q104,q105",
    "nomQ1Description": "Rear Admiral Margaret Grun Kibben, US Navy retired, was elected Chaplain of the US House of Representatives and was sworn in on January 3, 2021, by Speaker Nancy Pelosi as the 61st Chaplain and the first woman to serve in that position. History found her immediately, as she was involved in helping with the evacuation of Representatives during the Jan. 6 insurrection, three days into her job. She cited her combat experience in Afghanistan as helpful to her in knowing what to do to calm people and help them cope. \n\nChaplain Kibben also serves on the Board of the National Cathedral in Washington DC where she advises them on ministry to military veterans. After her retirement from the military and before her appointment to the House, she had established Virtue In Practice, LLC, a consulting business dedicated to moral, ethical, and spiritual executive leader advisement.\n\nChaplain Kibben is an ordained Presbyterian minister from the Philadelphia area who received her MDiv and DMin degrees from Princeton Theological Seminary. She entered active duty in the United States Navy in 1986.  She served as a Fellow at the United States Institute of Peace and holds a Masters Degree in National Security and Strategic Studies from the Naval War College.  Her personal awards include the Legion of Merit (2 awards), the Bronze Star, the Meritorious Service Medal (3 awards), and the Navy Commendation Medal (3 awards). She has enjoyed assignments with the Marines at Quantico and Camp Lejeune and Navy assignments at the Naval Academy, the USS San Diego (AFS-6), the Chaplain Resource Board in Norfolk, VA, and the U.S. Third Fleet in San Diego.  She deployed as the Command Chaplain, Combined Forces Command-Afghanistan, the first woman to hold this position.  Upon her return, Chaplain Kibben reported to the Office of the Chief of Navy Chaplains, first serving as the Director for Force Structure and Community Management, then as the Executive Assistant to the Chief of Navy Chaplains, and subsequently as the Chaplain of the Marine Corps/Deputy Chief of Navy Chaplains, again the first woman in these positions. Chaplain Kibben has served ashore, at sea, and abroad, with several deployments to the Mediterranean, as well as Norway, Turkey, and Afghanistan. \n\nIn 2014, Rear Admiral Kibben assumed her duties as the first woman to be Chief of Navy Chaplains. During her time in that position, she contracted with pastoral counselor and expert on military sexual trauma,Dr. Kristin Leslie, to travel to naval bases around the world to train chaplains in how to handle military sexual trauma, the only chief of chaplains to intentionally train chaplains under her command about this trauma. She was also among the first military chaplain leaders to learn about and speak on the new concept of moral injury in veterans.\n\nChaplain Kibben is married to Lieutenant Colonel Timothy J. Kibben, USMC (Retired). They reside in Alexandria, Virginia, with their daughter Lindsay Elizabeth.",
    "nomQ2": "q201,q202,q203",
    "nomQ2Description": "In addition to her innovative work to address military sexual trauma, Chaplain Kibben has held monthly Zoom meetings with members of the House to help them process and heal from the traumas of the insurrection. Her nonpartisan commitment to spiritual care has helped many House staffers and Representatives cope with their suffering and maintain their commitments to serving their country at a crucial time of violence and disruption to the nation's Capitol. Much of that work must, by necessity, remain below the radar of the fractious politics of our times, but her prayers during Jan. 2021 can be viewed at https://chaplain.house.gov/archive/index.html. Chaplain Kibben is modest, low-key, and carefully non-partisan so her contributions may not be as obvious as prophetic voices for change, but she has contributed greatly to the uncommon idea that women can be religious leaders at the highest levels of the military, among the most hypermasculine cultures in society, and succeed, paving the way for others to follow.",
    "nomQ3": "q301,q302",
    "nomQ3Description": "She is the first woman to pray in Congress as Chaplain of the House of Representatives, and due to her excellence and seriousness of purpose, she will not be the last. Her willingness to require a predominantly male Navy chaplaincy to understand military sexual trauma has impacted the lives of people of all genders in the military who have had to suffer its consequences.",
    "nomDeceased": "no",
    "nomAchieved": "yes",
    "nomAdditionalDescription": "Her contact information is: Margaret.Kibben@mail.house.gov.\n\nI have personally worked with her while she was Chief of Navy Chaplains and as Chaplain of the House."
  },
  "25": {
    "id": 25,
    "date": "2022-10-19",
    "authorFirst": "Eileen",
    "authorLast": "Rudd",
    "authorEmail": "EileenFitzRudd@gmail.com",
    "nomFirst": "Gladys",
    "nomLast": "West",
    "nomYOB": "1930",
    "category": "c700",
    "subcategory": "s707",
    "nomQ1": "q102",
    "nomQ1Description": "From Wiki...\nGladys Mae West (n\u00e9e Brown; born October 27, 1930[1]) is an American mathematician known for her contributions to the mathematical modeling of the shape of the Earth, and her work on the development of the satellite geodesy models that were eventually incorporated into the Global Positioning System (GPS).[2] West was inducted into the United States Air Force Hall of Fame in 2018. West was awarded the Webby Lifetime Achievement Award at 25th Annual Webby Awards for the development of the satellite geodesy models.[3][4]",
    "nomQ2": "q202",
    "nomQ2Description": "West's work has become an inescapable part of all of our daily lives let alone the changes to the fields of military, transportation and geography. Thru Gladys's mathematical calculations, GPS, was created.  Here are few ways GPS is used today: smart phones, watches, emergency roadside service and EMS, social media, finding things and people (pets and loved one) and finding a good local restaurant.  \n\nFrom Wiki:\n\nIn 1956, West was hired to work at the Naval Proving Ground in Dahlgren, Virginia, (now called the Naval Surface Warfare Center), where she was the second black woman ever hired and one of only four black employees.[7][5][2] West was a programmer in the Naval Surface Warfare Center Dahlgren Division for large-scale computers and a project manager for data-processing systems used in the analysis of satellite data.[12] Concurrently, West earned a second master's degree in public administration from the University of Oklahoma.[6]\n\nIn the early 1960s, she participated in an award-winning astronomical study that proved the regularity of Pluto\u2019s motion relative to Neptune.[13] Subsequently, West began to analyze data from satellites, especially satellite altimeters such as GEOS 3, putting together models of the Earth's shape. She became project manager for the Seasat radar altimetry project, the first satellite that could remotely sense oceans.[14][15] West consistently put in extra hours, cutting her team's processing time in half.[7] She was recommended for a commendation in 1979.[16]\n\n\nGladys West and Sam Smith look over data from the Global Positioning System at Dahlgren in 1985\nFrom the mid-1970s through the 1980s, West programmed an IBM 7030 Stretch computer to deliver increasingly precise calculations to model the shape of the Earth; an ellipsoid with additional undulations, known as the geoid.[8] Generating an extremely accurate geopotential model required her to employ complex algorithms to account for variations in gravitational, tidal, and other forces that distort Earth's shape. In her autobiography, West spoke of some of the complex problems she solved, which had proven too difficult for other members of the team.[9] West's model ultimately became the basis for the Global Positioning System (GPS).[13]\n\nIn 1986, West published Data Processing System Specifications for the Geosat Satellite Radar Altimeter, a 51-page technical report from The Naval Surface Weapons Center (NSWC). The guide was published to explain how to increase the accuracy of the estimation of geoid heights and vertical deflection, important components of satellite geodesy.[2] This was achieved by processing the data created from the radio altimeter on the Geosat satellite, which went into orbit on March 12, 1984.[11]\n\nWest worked at Dahlgren for 42 years, retiring in 1998.[7] After retiring, she completed a PhD in Public Administration from Virginia Tech.",
    "nomQ3": "q301",
    "nomQ3Description": "Gladys West has been overlooked during her career due to her sex color and sex.  She has overcome many hardships and like many stories of Women of the Hall her story needs to be told so that she can continue to inspire the young women of the future.\n\nFrom Wiki:\n\nDuring her career, she encountered many hardships because of racism against African Americans, primary of which was the lack of recognition she received while working, while her white coworkers received praise and added privileges. Within her biography, her disappointment at not being granted the projects that included travel and exposure is clear.[.",
    "nomDeceased": "no",
    "nomAchieved": "yes",
    "nomAdditionalDescription": "She has been inducted into the Air Force Hall of Fame.West was awarded the Webby Lifetime Achievement Award at 25th Annual Webby Awards for the development of the satellite geodesy models.[3][4]"
  },
  "26": {
    "id": 26,
    "date": "2022-10-19",
    "authorFirst": "Brenda",
    "authorLast": "Fraser",
    "authorEmail": "galaforce@msn.com",
    "nomFirst": "Patrice",
    "nomLast": "Billings",
    "nomYOB": "0",
    "category": "c600",
    "subcategory": "s602,s604",
    "nomQ1": "q101,q102,q103,q104,q105",
    "nomQ1Description": "This nominee was a female policy officer in St Louis County. She became the first female officer in the entire USA to become a helicopter pilot in 1984. She later became the Chief Pilot, received a Purple Heart, and was an expert sniper on the SWAT Team. She trained other officers to fly. She spoke to young girls and teens and inspired them to consider a career in aviation. She ran for State Senate in Missouri in 2018 as an out lesbian. That was the first time ever in our County, and rare even statewide. She is retired now and teaching kids to drive.",
    "nomQ2": "q201,q202,q203",
    "nomQ2Description": "Her accomplishments show that women can make great police officers and pilots. She served for 28 years, probably the longest in the country. her history is getting captured by the Missouri History Museum. \n\nShe has spoken to groups about Amelia Earhart and parallels with her own life. There was only 20 years difference between Amelia's disappearance and Patrice's birth.",
    "nomQ3": "q301,q302",
    "nomQ3Description": "Her police career created change for women to come for generations.\n\nPatrice was also the first female to graduate as TOP of the Class from Police Academy and First in Firearms. She proved that women can match and perform better than men, in some cases. \n\nShe is still an expert marksman.",
    "nomDeceased": "no",
    "nomAchieved": "yes",
    "nomAdditionalDescription": "She is humble and rare. She is philanthropic and helped raise substantial funds for domestic violence of which she is also a survivor. She was raised by a single mother and went on to make history. She ran a powerful senate campaign and inspired other women to run for state office. \n\nShe was a leader in local civic organizations like ZONTA international, and has established and funded a scholarship for women at the local community college."
  },
  "27": {
    "id": 27,
    "date": "2022-10-21",
    "authorFirst": "sonia",
    "authorLast": "ossorio",
    "authorEmail": "sonia@nownyc.org",
    "nomFirst": "Carolyn",
    "nomLast": "Maloney",
    "nomYOB": "0",
    "category": "c600",
    "subcategory": "s604",
    "nomQ1": "q101,q102,q103,q104,q105",
    "nomQ1Description": "In 1992, Congresswoman Maloney announced her run for Congress on the day the Planned Parenthood v. Casey\tdecision was released. Since that time, she has been a stalwart champion for women\u2019s rights in Congress, and a powerful example of leadership, dedication, and integrity. \n\nMost recently serving as the first female Chair of the House Committee on Oversight and Reform, Congresswoman Maloney\u2019s career has been defined as a trailblazing series of firsts, paving the way for a new generation of female leaders.  She was the first woman to represent New York City\u2019s 7th Council district, where she had a proven track record of fighting corruption and introduced New York State\u2019s first bill to give legal recognition to same-sex couples. She was the first City Council member to give birth while serving in office, rising against misogyny and fighting to pass inclusive paid family leave, a fight she continued onto the national stage.  \n\nCongresswoman Maloney has made an impact in politics that few other members of Congress have ever achieved. In addition to her position on the Oversight Committee, she was also the first woman to chair the Joint Economic Committee and continues to serve as a senior member of the House Financial Services Committee. She is also a former co-chair of the Congressional Caucus for Women\u2019s Issues. Congresswoman Maloney has succeeded in passing more than 75 measures either as stand-alone bills or as language incorporated into moving legislation. Of these bills, 12 have had presidential bill signings. She has repeatedly been rated the first, second, or third most effective member of Congress by the Committee on Effective Lawmaking and other independent rating agencies, including GovTrack\n\n\tMany of her accomplishments revolve around women\u2019s issues, specifically. Beginning in 1998, Congresswoman Maloney has led the effort to create a museum dedicated to the contributions of women. In 2014, the Congresswoman passed legislation authorizing a commission to research the potential creation of a women\u2019s history museum in Washington, D.C. After eighteen months, the commission unanimously found that the museum was needed, and in 2020, Congresswoman Maloney\u2019s bill to establish a women\u2019s history museum was signed into law. This museum will serve to immortalize the accomplishments of women and inspire future generations.\n\nCongresswoman Maloney is a champion of the Equal Rights Amendment and has introduced it in every session since the 105th Congress. She has fought for a woman\u2019s right to choose and is an outspoken supporter of women\u2019s reproductive rights. Congresswoman Maloney has used her platform as Chair of the House Committee on Oversight and Reform to hold hearings and shed light on these critically important issues during a time of historical upheaval of women\u2019s rights. \n\n\tOn breast cancer, Congresswoman Maloney\u2019s bill to provide annual mammograms for women on Medicare was included in the 1997 Balanced Budget Agreement. Rep. Maloney also passed a bill to establish a commemorative coin program at the U.S. Mint to raise an estimated $8.5 million for the Breast Cancer Research Foundation, which will save countless lives. \n\n\tCongresswoman Maloney has also been active on the issue of breastfeeding. While in Congress, Congresswoman Maloney successfully passed measures to allow WIC agencies to purchase breast pumps for new mothers and to ensure a woman\u2019s right to breastfeed on federal property. Her bill to require employers with more than 50 employees to provide a private space and unpaid time off during the workday to breastfeed was also included in the Affordable Care Act, as was her bill to create Women\u2019s Health Offices in five Federal agencies, including the Department of Health and Human Services. \n\n\tCongresswoman Maloney has been similarly active on issues related to sexual assault. In 2004, her Debbie Smith Act was signed into law, which created a grant program for state and local law enforcement agencies to conduct forensic analysis of DNA evidence collected from crime scenes, including untested rape kits. Thanks to Congresswoman Maloney\u2019s work, the Debbie Smith Act was subsequently reauthorized in 2008, 2014, and 2019, and the National Institute of Justice reports that since 2005, Debbie Smith funding is responsible for 192,000 \u2013 or about 42% - of DNA matches in the FBI database. The Debbie Smith Act has been called \u201cthe most important anti-rape legislation in history.\u201d Congresswoman Maloney was also successful in adding two pieces of original legislation to the 2013 Violence Against Women Act Reauthorization, including protections for older women and a bill that expanded the scope of reporting, response, and prevention education requirements around sexual violence for institutions of higher education, which remains a critical issue today.\n\n\tThroughout her 30 years in Congress, Congresswoman Maloney has also passed bills on other major issues, including funding and support for 9/11 survivors and responders. In 2010, Congresswoman Maloney authored and passed the James Zadroga 9/11 Health and Compensation Act, which authorized and funded the World Trade Center Health Program to provide medical monitoring and treatment to 9/11 responders and survivors. The bill also re-opened the September 11th Victim Compensation Fund to ensure compensation for 9/11 responders and survivors as well as their families. In 2015 and 2019, Congresswoman Maloney passed two additional bills to extend these programs to 2090. In addition, as co-founder of the House 9/11 Commission Caucus, Congresswoman Maloney helped author and pass legislation to create the 9/11 Commission and, later, to implement all of the 9/11 Commission\u2019s recommendations for improving intelligence gathering, which has been described as the most influential intelligence bill in decades.\n\n\tSome of the Congresswoman\u2019s other major accomplishments include passing the Credit CARD Act, also known as the Credit Cardholders\u2019 Bill of Rights. This legislation leveled the playing field between consumers and credit card companies by banning practices that have been determined to be unfair, deceptive, and anti-competitive by the Federal Reserve. And according to the Consumer Financial Protection Bureau (CFPB), her legislation has saved consumers more than $16 billion annually since it was signed into law in 2009. \n\nCongresswoman Maloney has also delivered more than $10 billion in federal aid to New York City, including billions of dollars for the two largest transit construction projects in the nation, the Second Avenue Subway and the East Side Access project, both of which run through her district, and have helped create thousands of jobs in New York. \n\n\tAs a former teacher, education has also been of the utmost importance to the Congresswoman. In 2020, Congresswoman Maloney introduced and passed the Never Again Education Act, which expands the U.S. Holocaust Memorial Museum\u2019s education programming to teachers nationwide, requiring the museum to develop and disseminate resources to improve awareness and understanding of the Holocaust and its lessons. She has also introduced the LGBTQI+ and Women\u2019s History Education Act, which serves to promote and support the teaching of these underrepresented histories in classrooms. Locally, she has worked to resolve education access issues, and supported the creation of multiple schools, including the academically rigorous Eleanor Roosevelt High School established in 2002. \n\nFrom her classroom in East Harlem to the halls of Congress, Congresswoman Maloney has never stopped fighting for what is right and has never given up in the face of adversity. Her actions have uplifted women and have inspired a brave generation of future leaders - and that includes me, and so many others. Her determination, her support of issues and peoples when there would be no credit for it, her ability to see the long game and achieve small gains that one day make what seemed impossible, inevitable.",
    "nomQ2": "q201,q202,q203",
    "nomQ2Description": "When Congresswoman Maloney first entered Congress in 1993, she was one of 47 women in the House of Representatives. Her previously outlined tenure of firsts paved the way and inspired more women to run, having a significant impact across the country. Today, there are now 122 female members in the House.\n\nThe Congresswoman\u2019s achievements have encouraged female leadership nationally, at every level of government. Her tackling of prejudice against women, such as being unable to hold office and have a child, have been constant evidence of women\u2019s capabilities. Her time on the New York City Council has proven to be more than just locally significant, as it has inspired other women to become involved in local government both in New York City and beyond. \n\nCongresswoman Maloney\u2019s entire legislative record in Congress has had national impact, but her work on 9/11 healthcare particularly stands out. The Congresswoman\u2019s James Zadroga 9/11 Health and Compensation Act authorized and funded the World Trade Center Health Program to provide medical monitoring and treatment to 9/11 responders and survivors. Currently, this program serves more than 118,000 responders and survivors who live in all fifty states and live in 434 out of 435 Congressional districts. \n\nCongresswoman Maloney has also made outstanding contributions to the United States economy. Since being elected to Congress, she has worked to modernize financial services laws and regulations while strongly advocating for consumer protections. As Chair of the Joint Economic Committee in the 111th Congress, she held a series of hearings and published reports to assess women\u2019s role in the economy, and to inform the next set of policy decisions about how best to create an economy that fully unleashes the economic potential of women. These hearings have helped both policymakers and leaders in the private sector determine whether policies promote or inhibit women\u2019s ability to be powerful contributors to economic growth.\n\nOn a global level, Congresswoman Maloney passed legislation that included $60,000,000 for programs benefitting Afghan women and girls, and $5,000,000 for the Afghan Independent Human Rights Commission. She has been a strong supporter of the UNFPA (United Nations Population Fund) and has fought to reinstate and continue American funding of the organization to help women around the world gain access to family planning, safer pregnancies and childbirth, and better health care. In 2002, Congresswoman Maloney also passed legislation to provide overseas voters with absentee ballots and establish an office in each state to respond to overseas voter inquiries.\n\nCongresswoman Maloney is also the founder and Co-Chair of the Congressional Caucus on Hellenic Issues. and represents one of the largest Greek populations in the world, outside of Cyprus and Greece. The Hellenic Caucus serves to bring a renewed congressional focus on key diplomatic, military, and human rights issues in this critical part of the world. \n\nThe Congresswoman has been a fierce defender of international human rights throughout her career and has worked with her congressional colleagues to combat violations throughout the world in places such as Burma, Mexico, and Sudan.  She also serves as a member of the Congressional Caucus on Armenian Issues, working to strengthen relations between the United States and Armenia. Most recently, she has introduced legislation to encourage education of the Armenian Genocide, providing teachers across the United States with the resources they need to communicate the atrocities of genocide and the consequences of intolerance and hate.\n\nCongresswoman Maloney has not only worked tirelessly to support our nation but has contributed significantly to the global community in the fight for undeniable human rights. Her legislative achievements have been featured in three films: the documentary The Card Game, the documentary Overdrawn!,  and the movie A Life Interrupted, chronicling the story of Debbie Smith. Congresswoman Maloney is also the author of Rumors of our Progress Have Been Greatly Exaggerated: Why Women\u2019s Lives Aren\u2019t Getting any Easier and how we can Make Real Progress for Ourselves and Our Daughters, which has been used as a textbook in women\u2019s studies courses.",
    "nomQ3": "q301,q302",
    "nomQ3Description": "Congresswoman Maloney\u2019s achievements have and will have enduring value for years to come. Throughout her time in Congress, Representative Maloney has succeeded in passing more than 75 measures either as stand-alone bills or as language incorporated into moving legislation. These bills have been permanently signed into law and many include permanent or near-permanent provisions. \n\nWithin her district, Congresswoman Maloney is responsible for the renewed attention and action on the Second Avenue Subway, which has been rated by the Federal Transit Administration as one of the best in the country. If not for the Congresswoman\u2019s efforts, New York City would not have stations on Second Avenue and 63rd Street, 72nd Street, 86th Street, and 96th Street. Thanks to the Congresswoman\u2019s efforts, the second phase of this project is also currently in process, and once completed, Phase 2 will bring Q Train service to 125th Street, making it easier for folks to travel and spurring economic growth and jobs across the city. Additionally, due to the laws that the Congresswoman passed in 2015 and 2019, healthcare and compensation for 9/11 responders, survivors, and their families is guaranteed until 2090. \n\nOn the national level, Congresswoman Maloney is responsible for a historic piece of legislation which will revitalize and support the U.S. Postal Service for years to come. The Postal Service Reform Act provides postal workers with their own postal service health benefits program and enacts transparency requirements to keep Congress appraised of the U.S. Postal Service\u2019s performance. As a result, the Post Office is set to receive nearly $50 billion in financial relief over the next decade.\n\nThe Congresswoman\u2019s work to build a women\u2019s museum will immortalize women\u2019s history and inspire future generations. The Smithsonian Institution is currently in the process of choosing a site for the museum in Washington D.C. that will be visited by billions of people over centuries. \n\nDuring a time where women\u2019s rights are under attack like never before, Congresswoman Maloney has laid out a 12-point plan to restore and expand abortion access, protect birth control, and ensure other privacy rights on the federal level. This plan includes certifying and publishing the Equal Rights Amendment, which the Congresswoman believes will result in a constitution that prohibits discrimination against women and empowers Congress to create laws that address issues like domestic violence and equal pay in ways they currently cannot. \n\nThe plan also includes legislative action based on two of Congresswoman Maloney\u2019s bills: the Access to Birth Control, which prevents pharmacies from refusing to provide contraception, and the Stop Anti-Abortion Disinformation Act, which goes after crisis pregnancy centers that spread disinformation to stop people from getting abortions. In addition, the plan aims to provide greater access to medication abortion and urges the Senate passage of legislation to protect abortion rights, contraception, and same-sex marriage. \n\nCongresswoman Maloney\u2019s 12-point plan has laid the groundwork in the fight to restore and expand women\u2019s rights and will be crucial in the next chapter of our nation\u2019s history. \n\nShe has also created a legacy by leading the effort to recognize the harms, and criminality of one of the severest forms of human rights violations - human trafficking. She led the effort to pass the TVPA, Trafficking Victims Protection Act, and to ensure that the law was implemented and that the government response was in place. That means services, public education, training of law enforcement, judges, lawmakers at all levels of government.",
    "nomDeceased": "no",
    "nomAchieved": "yes",
    "nomAdditionalDescription": "As a human rights activist focused on women's human rights, I have had the privilege to work with and learn from  Congresswoman Maloney for the past two decades. Without question, she is one of the great leaders of her time, having made indelible changes to the advancement of women's equal rights and to the fabric of our democracy. She has changed the course of history, and of many lives, including those like mine, younger women and men advocates, legislators, and the many aspiring staff members she has mentored in the course of her unparalleled career as one of the most productive members of Congress. By way of her eloquence, I have learned  that advancing women's rights and opportunities directly leads to strengthening our country and economy and the fabric of our future, and that the public must be reminded of this truth continually. I have learned from her that grit, perseverance and hard work win the day, and that there are no dead ends, only momentary setbacks or delays. Ms. Maloney is not one to be deterred by setbacks, but rather, to be bold and self-assured and have the intellectual prowess to sharpen one's argument and ability to demonstrate significance. Opportunity will arise. New avenues, approaches and innovation will follow. These are just a few of the lessons I have internalized and will, in turn, pass on to those who look to me for guidance, just as I have turned to Ms. Maloney. Congresswoman Carolyn Maloney is most decidedly a great American woman, who has changed the course of history for the women of the United States and beyond. Her enduring legacy will shine brighter with each passing year. As someone who has had a front row seat to her incredible journey, I  feel certain of that. She is an American political icon who richly deserves the recognition of being named to the illustrious National Women's Hall of Fame."
  },
  "28": {
    "id": 28,
    "date": "2022-10-29",
    "authorFirst": "Dorthea",
    "authorLast": "King-Simpson",
    "authorEmail": "Dorthea@Deksconsulting.com",
    "nomFirst": "Liz",
    "nomLast": "Cheney",
    "nomYOB": "0",
    "category": "c600",
    "subcategory": "s604",
    "nomQ1": "q101",
    "nomQ1Description": "Was a member of Congress, Served as a Republican leader.",
    "nomQ2": "q201",
    "nomQ2Description": "Chose people over politics. Stopd up for Democracy, and bravely served on the Jan 6th Committee.",
    "nomQ3": "q302",
    "nomQ3Description": "She chose bi-partisan politics, to save our democracy in the midst of a toxic environment, knowing that she would not be popular, could and did lose her seat in the Republican Party, and would become  a political target.",
    "nomDeceased": "no",
    "nomAchieved": "yes",
    "nomAdditionalDescription": "As a democrat and woman of color, her Bravery is beyond inspiring."
  },
  "29": {
    "id": 29,
    "date": "2022-10-30",
    "authorFirst": "Jess",
    "authorLast": "Nadelman",
    "authorEmail": "jessnadelman@gmail.com",
    "nomFirst": "Liz",
    "nomLast": "Cheney",
    "nomYOB": "0",
    "category": "c600",
    "subcategory": "s604",
    "nomQ1": "q103,q104",
    "nomQ1Description": "Ms. Cheney stood up for the Constitution and our democracy at a personal political cost to her, no less enduring threats. Although I do not agree with many of the policies she supports, there is literally no Congressperson who has shown such courage and working for the the good of this country, its institutions and citizens.",
    "nomQ2": "q203",
    "nomQ2Description": "Her resolve, leadership and intelligence contributed to bringing to light the crimes against this country. She continues in the work of saving our democracy even as she lost her seat in Congress.",
    "nomQ3": "q302",
    "nomQ3Description": "Without her leadership and again, courage, this country would have an even greater chance of becoming an autocracy.",
    "nomDeceased": "no",
    "nomAchieved": "yes",
    "nomAdditionalDescription": "As a liberal it was a difficult decision to nominate Liz Cheney as I noted above. But my or the members of the nominating committee's political and cultural views should not . . .better, must not. . .off handedly deny any candidate their rightful place in the Hall. \nThank you for your consideration."
  }
}

export default nominations;